apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://%%MASTER_IP%%:8080
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: ""
  name: kubelet-context
current-context: kubelet-context